# Generated by Django 5.1.3 on 2024-11-30 01:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=2000)),
                ('imagem', models.ImageField(upload_to='imagens_cursos')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('visualizacoes', models.ImageField(default=0, upload_to='')),
                ('categoria', models.CharField(choices=[('DESENVOLVIMENTOWEB', 'Desenvolvimento Web'), ('ANALISEDEDADOS', 'Análise de Dados'), ('PROGRAMACAO', 'Programação'), ('BANCODEDADOS', 'Banco de Dados'), ('APRESENTACAO', 'Apresentação'), ('OUTROS', 'Outros')], max_length=30)),
                ('avaliacao', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('numero_aulas', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('quantidade_inscritos', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
