# Generated by Django 5.1.3 on 2024-11-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
